### PR TITLE
feat: add support for furigana

### PR DESCRIPTION
**Pull request by tinarskii**
1. Add support for furigana (Totally safe, trust me bro)
2. Set `cursor-pointer` to `Kana/Romaji` and `Lyrics/Name` button
3. Add next song (50th opening of Detective Conan)
4. Tinker with ur files (not breaking)
5. Broke your tests lol

# 😱This will happen if u accept this pull request (shocking):
image

### CODE REVIEW

**Review by Leomotors — APPROVED** [review]
image

**Comment by SaltyAom** [comment]
image

**Comment by tinarskii** [comment]
> image

**Comment by tinarskii** [comment]
5782E75C-B852-4EE2-8623-3457A694ECC4

**Pull request merged**
