### PR TITLE
add anisong  Girls last tour - More One Night

### PR DESCRIPTION
**Pull request by wasdee**

### CODE REVIEW

**Comment by wasdee** [comment]
hi cunniers @CunnyDev/millennium  could you review my PRs file?

**Review by Leomotors — COMMENTED** [review]
Should it start with `ke`/`け`?

**Comment by wasdee** [comment]
Okay thx

**Comment by wasdee** [comment]
updated. it should start with `ke` now. @Leomotors 

image

**Comment by Leomotors** [comment]
@cloudflare-pages where deploy preview

**Pull request merged**
